// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Android Gradle Plugin
        classpath 'com.android.tools.build:gradle:8.2.0'
        
        // Navigation Safe Args Plugin
        classpath 'androidx.navigation:navigation-safe-args-gradle-plugin:2.7.6'
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
